import Timer from "../components/timer.js";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar.js";
import Todo from "../components/todo.js";
import Notes from "../components/notes.js";
import DayPlanner from "../components/dayplanner.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Productivity Together</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.container}>
        <div className={styles.componentsContainer}>
          <div className={styles.timerContainer}>
            <Timer />
            <DayPlanner />
          </div>
          <div className={styles.todoContainer}>
            <Todo />
          </div>
          <div className={styles.friendsContainer}>
            <Notes />
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
